
services:
  ollama-server:
    image: ollama/ollama:latest
    container_name: ollama-server
    command: serve
    ports:
      - "11434:11434"
    volumes:
      - C:/Users/nauna/Desktop/lome/volume:/root/.ollama
    restart: always
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask-app
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - OLLAMA_HOST=ollama-server
      - OLLAMA_PORT=11434
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - FLASK_RUN_HOST=0.0.0.0
    depends_on:
      - ollama-server
      - redis
    networks:
      - app-network

networks:
  app-network:
    driver: bridge