services:
  ollama-server:
    image: ollama/ollama:latest
    container_name: ollama-server
    # Commande correcte pour ollama
    command: serve
    ports:
      - "11434:11434"
    volumes:
      - C:/Users/nauna/Desktop/lome/volume:/root/.ollama
    restart: always
    networks:
      - app-network

  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask-app
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - OLLAMA_HOST=ollama-server
      - OLLAMA_PORT=11434
    depends_on:
      - ollama-server
    networks:
      - app-network

networks:
  app-network:
    driver: bridge